# Generated by Django 3.2.25 on 2025-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stream',
            field=models.CharField(choices=[('a', 'Stream A'), ('b', 'Stream B')], max_length=1),
        ),
    ]
