# Generated by Django 3.2.25 on 2025-06-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='preferred_stream',
            field=models.CharField(choices=[('a', 'Stream A'), ('b', 'Stream B')], default='a', help_text='The stream the instructor prefers to view.', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stream',
            field=models.CharField(choices=[('a', 'Stream A'), ('b', 'Stream B')], max_length=1),
        ),
    ]
