# Generated by Django 3.2.25 on 2025-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customuser_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='preferred_stream',
            field=models.CharField(choices=[('a', 'Stream A'), ('b', 'Stream B')], default='a', help_text='The stream the instructor prefers to view.', max_length=1),
        ),
    ]
