# Generated by Django 3.2.25 on 2025-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_b', '0002_leveladvisor_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_year_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='is_extra_year',
            field=models.BooleanField(default=False),
        ),
    ]
