# Generated by Django 3.2.25 on 2025-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_b', '0002_auto_20250623_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='stream_b.Course'),
        ),
    ]
