# Generated by Django 3.2.25 on 2025-04-03 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('courseCode', models.CharField(blank=True, max_length=15, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('C', 'Compulsory'), ('E', 'Elective'), ('R', 'Required')], default='C', max_length=40, null=True)),
                ('category', models.CharField(blank=True, choices=[('nursing course', 'NC'), ('life science', 'LS'), ('non-nursing course', 'NNC')], default='NNC', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.college')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('year', models.CharField(max_length=9)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stream_a_student', serialize=False, to='common.customuser')),
                ('otherNames', models.CharField(blank=True, max_length=80, null=True)),
                ('surname', models.CharField(blank=True, max_length=80, null=True)),
                ('matricNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('jambNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], max_length=15, null=True)),
                ('studentPhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('passport', models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='', verbose_name='image')),
                ('student_status', models.CharField(choices=[('inprogress', 'In Progress'), ('failed', 'Failed'), ('graduated', 'Graduated')], default='inprogress', max_length=100)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.college')),
                ('currentLevel', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentLevel', to='stream_a.level')),
                ('currentSemester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='stream_a.semester')),
                ('currentSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='stream_a.session')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.department')),
                ('entrySession', models.ManyToManyField(related_name='entrySession', through='stream_a.Enrollment', to='stream_a.Session')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='stream_a.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instructor_remark', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.course')),
                ('semester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.semester')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.session')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.student')),
            ],
        ),
        migrations.CreateModel(
            name='LevelAdvisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stream_a_advisor', serialize=False, to='common.customuser')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('passport', models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.level')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.session'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ManyToManyField(related_name='courses', to='stream_a.Programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.semester'),
        ),
        migrations.CreateModel(
            name='confirmRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('totalUnits', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_a.level')),
                ('semester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.semester')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.session')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade_type', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('total_point', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('grade_remark', models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('carried_over', models.BooleanField(default=False)),
                ('result_date', models.DateField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='stream_a.registration')),
            ],
            options={
                'unique_together': {('registration', 'attempt_number')},
            },
        ),
    ]
