# Generated by Django 3.2.25 on 2025-06-23 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='currentSemester',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='stream_a.Course'),
        ),
        migrations.AddField(
            model_name='leveladvisor',
            name='stream',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='entryLevel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_a.level'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_year_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='genoType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_extra_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='localGovtArea',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='modeOfEntry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='primaryEmail',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stateOfOrigin',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
