# Generated by Django 3.2.25 on 2025-04-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0002_auto_20250405_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entryLevel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='genoType',
        ),
        migrations.RemoveField(
            model_name='student',
            name='localGovtArea',
        ),
        migrations.RemoveField(
            model_name='student',
            name='modeOfEntry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primaryEmail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stateOfOrigin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentEmail',
        ),
    ]
