# Generated by Django 3.2.25 on 2025-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0002_auto_20250623_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
