# Generated by Django 3.2.25 on 2025-07-08 10:48

from django.db import migrations

def populate_course_title(apps, schema_editor):
    Registration = apps.get_model('stream_a', 'Registration')
    for registration in Registration.objects.all():
        if registration.course:
            registration.course_title = registration.course.title
            registration.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0003_registration_course_title'),
    ]

    operations = [
        migrations.RunPython(populate_course_title, reverse_code=migrations.RunPython.noop)
    ]
