# Generated by Django 3.2.25 on 2025-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0004_auto_20250405_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveladvisor',
            name='stream',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
