# Generated by Django 3.2.25 on 2025-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0005_leveladvisor_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='stream_a.Course'),
        ),
    ]
