# Generated by Django 3.2.25 on 2025-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0005_auto_20250708_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='courseCode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
