# Generated by Django 3.2.25 on 2025-05-07 13:25

from django.db import migrations, models
import django.utils.timezone


def set_default_time(apps, schema_editor):
    Registration = apps.get_model('stream_a', 'Registration')
    for reg in Registration.objects.all():
        if reg.registration_date:
            # Convert date to datetime (e.g., set time to 00:00:00)
            reg.registration_date = timezone.datetime.combine(
                reg.registration_date,
                timezone.datetime.min.time()
            )
            reg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0006_course_prerequisites'),
    ]

    operations = [
        migrations.RunPython(set_default_time, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
