# Generated by Django 3.2.25 on 2025-07-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0007_auto_20250708_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
    ]
