# Generated by Django 3.2.25 on 2025-07-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0008_remove_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='courseLevel',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='courseSemester',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
