# Generated by Django 3.2.25 on 2025-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_a', '0009_auto_20250709_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='courseCategory',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
